export const settingFont = {
    regular: 400,
    medium: 500,
    bold: 700,
};

export const TextStyles = {
    displayXl: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 60,
            lineHeight: '72px',
            letterSpacing: '-0.02em',
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 60,
            lineHeight: '72px',
            letterSpacing: '-0.02em',
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 60,
            lineHeight: '72px',
            letterSpacing: '-0.02em',
        },
    },
    displayLg: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 48,
            lineHeight: '60px',
            letterSpacing: '-0.02em',
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 48,
            lineHeight: '60px',
            letterSpacing: '-0.02em',
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 48,
            lineHeight: '60px',
            letterSpacing: '-0.02em',
        },
    },
    displayMd: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 36,
            lineHeight: '44px',
            letterSpacing: '-0.02em',
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 36,
            lineHeight: '44px',
            letterSpacing: '-0.02em',
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 36,
            lineHeight: '44px',
            letterSpacing: '-0.02em',
        },
    },
    displaySm: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 30,
            lineHeight: '38px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 30,
            lineHeight: '38px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 30,
            lineHeight: '38px',
            letterSpacing: 0,
        },
        mediumItalic: {
            fontWeight: settingFont.medium,
            fontSize: 30,
            lineHeight: '44px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
    },
    displayXs: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 24,
            lineHeight: '32px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 24,
            lineHeight: '32px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 24,
            lineHeight: '32px',
            letterSpacing: 0,
        },
        mediumItalic: {
            fontWeight: settingFont.medium,
            fontSize: 24,
            lineHeight: '36px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
    },
    textXl: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
        },
        normalItalic: {
            fontWeight: settingFont.regular,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        mediumItalic: {
            fontWeight: settingFont.medium,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        boldItalic: {
            fontWeight: settingFont.bold,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        normalUnderlined: {
            fontWeight: settingFont.regular,
            fontSize: 20,
            lineHeight: '30px',
            letterSpacing: 0,
            textDecoration: 'underline',
        },
    },
    textLg: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
        },
        normalItalic: {
            fontWeight: settingFont.regular,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        mediumItalic: {
            fontWeight: settingFont.medium,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        boldItalic: {
            fontWeight: settingFont.bold,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        mediumUnderlined: {
            fontWeight: settingFont.medium,
            fontSize: 18,
            lineHeight: '28px',
            letterSpacing: 0,
            textDecoration: 'underline',
        },
    },
    textMd: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
        },
        normalItalic: {
            fontWeight: settingFont.regular,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        mediumItalic: {
            fontWeight: settingFont.medium,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        boldItalic: {
            fontWeight: settingFont.bold,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
            fontStyle: 'italic',
        },
        normalUnderlined: {
            fontWeight: settingFont.regular,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
            textDecoration: 'underline',
        },
        mediumUnderlined: {
            fontWeight: settingFont.medium,
            fontSize: 16,
            lineHeight: '24px',
            letterSpacing: 0,
            textDecoration: 'underline',
        },
    },
    textSm: {
        normal: {
            fontWeight: settingFont.regular,
            fontSize: 14,
            lineHeight: '20px',
            letterSpacing: 0,
        },
        bold: {
            fontWeight: settingFont.bold,
            fontSize: 14,
            lineHeight: '20px',
            letterSpacing: 0,
        },
        medium: {
            fontWeight: settingFont.medium,
            fontSize: 14,
            lineHeight: '20px',
            letterSpacing: 0,
        },
        semiBoid: {
            fontWeight: settingFont.bold,
            fontSize: 14,
            lineHeight: '22px',
            letterSpacing: 0,
        },
    },
};